import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, NetworkFirst } from "workbox-strategies";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

registerRoute(
  ({ url }) => url.pathname === "/memes",
  new NetworkFirst(),
  "GET"
);

registerRoute(
  ({ url }) => url.pathname === "/memes/backgrounds",
  new NetworkFirst(),
  "GET"
);

registerRoute(
  /.*.(?:png|jpg|jpeg|svg)$/,
  new CacheFirst({
    cacheName: "meme-images",
  }),
  "GET"
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
